name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Upload html test report
        uses: actions/upload-artifact@v2
        with:
          name: lint.html
          path: app/build/reports/lint-results-debug.html

  detekt:
    ## 4
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: detekt
        uses: alaegin/Detekt-Action@v1.22.0
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          detekt_config: config/detekt/detekt.yml

  ##detekt:
  ##  runs-on: ubuntu-latest
  ##    steps:
  ##      - name: Clone repo
  ##        uses: actions/checkout@v2
  ##      - name: detekt
  ##        uses: alaegin/Detekt-Action@v1.22.0